name: Running Unit Test, Build Docker Image,  Push To Docker Hub and Deploy To EC2

on:
  pull_request:
    branches:
      - 'master'
  push: 
    branches:
      - 'master'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: running unit test
      run: go test ./controller -cover
  build-push-docker:
    name: "Build image and push to registry"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: docker build -t rizkysr90/book_library:1.0.0 .
    - name: login registry docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: push image to registry docker hub
      run: docker push rizkysr90/book_library:1.0.0